### ISSUE TITLE
Scrolling is stuck after changing layout

### ISSUE THREAD

**Issue by antelle** [shysaur/Fragaria#102]
Hi!
Thanks for this awesome live fork! I'm trying to build something cool using it.
Here's the only thing I spotted: after changing `lineWrap` or `showsGutter`, i.e. properties causing text reflow, scrolling is sometimes stuck in the middle of text (it doesn't go below it), the other part of text is cut off. It's not stable, however happens quite often for me. It looks like content height is not recalculated. After making any change, or selecting, or resizing the window, it comes back to normal.
Video example: https://monosnap.com/file/FnkL3axSRym2iwStJ06Zqo04UiJfPu
This also happens on `Fragaria Prefs` example app included into your project, built without any changes.
My environment:
- macOS High Sierra 10.13.2
- Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
- Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
- Apple LLVM version 9.0.0 (clang-900.0.39.2)
- Target: x86_64-apple-macosx10.9

After some investigation I noticed that adding
```objc
[[self layoutManager] ensureLayoutForTextContainer:textContainer];
```
[in SMLTextView::updateLineWrap](https://github.com/shysaur/Fragaria/blob/master/SMLTextView.m#L1421), after:
```objc
[[self layoutManager] textContainerChangedGeometry:textContainer];
```
fixes the issue, but I haven't checked it completely yet.

**Comment by shysaur** [comment]
I am aware of this issue, but as far as I can tell, it is a bug in NSTextView itself (I can reproduce it consistently by opening a large enough file in TextEdit, like the tic-tac-toe.asm example).

At the moment I have not attempted to work around it because I hoped Apple would fix it in a future update. But, since Apple's responsiveness when fixing bugs is (and always has been) too slow and 10.13 has been out for a while now, if I have the time, I will try to implement some hack that "fixes" it.

**Comment by shysaur** [comment]
> tic-tac-toe.asm example

Sorry I was mixing up one project with another XP
The file I am referring to is https://github.com/shysaur/Tricky68k/raw/master/Motorola68kPlatform/Examples/Base.lproj/tic-tac-toe.s

**Comment by antelle** [comment]
Cool, glad to hear you're aware of it.
Thanks again for your fast response and supporting this fork!

**Comment by antelle** [comment]
After playing with it and switching modes for some time, I can confirm that the change described in my first comment (with `ensureLayoutForTextContainer`) fixed the issue for me. However I'm not sure if it will work everywhere.

**Comment by shysaur** [comment]
I think I found a more general fix; please pull commit 358776d and check if it works for you. With this fix, Fragaria should now behave exactly as it did under macOS 10.12.

This commit will be tagged as a release as soon as I get your confirmation.

**Comment by antelle** [comment]
Pulled this commit, it didn't fix it unfortunately (on my app and `Fragaria Preferences`).

**Comment by shysaur** [comment]
Are you sure about that? Try scrolling to the end of the text view; at that point it should realise that there's more text and expand by itself. This is exactly how every NSTextView behaved in macOS 10.12 IIRC.

I have a more radical patch in testing, but it massively decreases the performance of anything that requires a relayout, and I don't want to go that far unless it's absolutely necessary.

**Comment by antelle** [comment]
Well, at least I see the issue after recompiling with the fix.
You can send me a patch with some logging if you would like to, I can test it.

**Comment by antelle** [comment]
I just noticed one thing: now, when you scroll to bottom, it scrolls to some point (the same as before), then bounces back and after “elastic effect” has completed, it recalculates, but it remains where it was. You can see a white area below text during the first elastic bounce. Which is not nice, if you scroll a file with one gesture, you have to scroll it twice to get to the end.

**Comment by antelle** [comment]
Here's a demo: https://monosnap.com/file/dHax1mCFEcQFKU7QobL78s74n3ToQo
I used this file to test, if it matters: https://github.com/antelle/argon2-browser/blob/master/lib/argon2.js

**Comment by shysaur** [comment]
> it scrolls to some point (the same as before), then bounces and after elastic effect has completed, it recalculates

This is what I expected to see. I concur that it's disgusting, but NSTextView has behaved like that for 2 major OS releases at this point, and the delayed recalculation is an unrelated issue from an implementation point of view.

The problem is that NSTextView re-layouts itself only if it anticipates that an area not laid out before will appear on screen. But it does it far too lazily. It used to work nicely in 10.11, but something broke since then and Apple has not fixed it yet (which is a recurring trend...).

I tried to work around it in commit ae1e1ba by manually requesting layout in advance in SMLTextView. Let me know if it also works well enough for you.

EDIT: commit cc24dec fixes an embarrassing mistake which made the prefetching far too aggressive.

**Comment by antelle** [comment]
Yeah this works, thanks! 💯 
There's a small glitch in the beginning of scrolling though (vertical scrollbar changes height), but it's much better compared to the previous behavior. And I guess, it will disappear in future, once the layout bug is fixed.

**Comment by shysaur** [comment]
Great! Thank you for the help.
