### ISSUE TITLE
Image cleanup

### ISSUE THREAD

**Issue by shysaur** [shysaur/Fragaria#13]
Currently, image resources in Fragaria are of varying quality and origin. They should be redrawn/updated to be all consistent with each other and in line with Yosemite's aesthetic.

**Comment by balthisar** [comment]
I pulled the .icns from a previous version of Mac OS X -- not sure if 10.9 or 10.8. I'll look for updated resources in Yosemite. 

I wouldn't mind eliminating editor-warning.png entirely. It's only non-retina. I added the .icns because the original editor-warning.png was so bad, but I felt I didn't want to replace the original, and then it became easy just to include a larger set and make any of them work. I only left the original in so that the change would be transparent.

It would make the code _slightly_ cleaner to remove the PNG entirely, and choose one of new icons as the default. I added .icns rather than .png.

I like the idea of .icns because the Apple icons have several resolutions. In the future instead of using only 16x16 we might consider another size based on line height or font size.

Edit: Also the line markers could be updated. I will look at trying to make a "master" SVG or similar.

What are your thoughts on line marker types? It seems relatively simple to add support for different arbitrary markers (e.g., breakpoint, breakpoint disabled, current execution point, etc.). It's probably elementary to color them without separate images, too. But... would we implement multiple delegates, or simply change the delegate API a bit so that it can return the desired line marker type? In case of multiple markers for the same lines, this gives all of the decision-making to the delegate (good thing).

On that note, maybe not a bad idea to replace the current errors with an error-delegate instead. The means I used to address multiple warning styles is quite arbitrary.

**Comment by shysaur** [comment]
Yes, I was thinking about removing editor-warning.png and replacing the line markers when I wrote this issue. The image format doesn't matter much, especially if/when we'll make an asset library for Fragaria.

About line markers, I'd add some methods in the delegate to provide an NSSet of a new MGSLineMarker class instances, with an NSImage property for the line marker. The NSImage returned may be a standard image loaded from a file (which will be drawn pinned to the right edge and not stretched) or an image with a custom NSImageRep, and the image rep will care about stretching the line marker. This gives great flexibility to the user. (NoodleKit, where I got the basis for the new line number gutter implementation, used the custom image rep approach for drawing line markers)

It would be inappropriate to replace the current errors with an error delegate. There are multiple reasons for that.
- First, the current implementation is already simple enough to use, and custom setters for an immutable object are the fastest way to be notified of changes. With delegates, the delegate would have to notify Fragaria about changes to the errors, and this is by definition the reverse of the delegate pattern: a setter.
- Look at how Apple itself uses delegates. For example, NSWindowDelegate does not have a method for putting subviews in its NSWindow (this is the same of setting an array to add errors to display in Fragaria), but NSWindowDelegate has a method for deciding if NSWindow is allowed to be closed (and this is the same of Fragaria sending a notification for adding line markers).
- Also, look at how delegates fit in the MVC model. The user clicks on the NSWindow to decide it has to be closed (view->controller->view feedback), but the user can't directly interact with compiler errors, because they are read-only by definition; only a recompile can clear (or, more appropriately, replace) them (model->controller->view action). Delegates are for feedback; but we have no feedback here, so they are inappropriate.

Last thing: this has gone offtopic. I won't comment about delegates again in this thread.

**Comment by balthisar** [comment]
That's an excellent Stack Exchange type of answer, and I'm impressed (the good type of answers, I mean; not the type people spend three minutes Googling for in search of points).

I'll open a new issue about warning buttons in the document body.

**Comment by shysaur** [comment]
I plan to redraw the icons to PDF line art, which should look a bit better given the usual scale of display.

**Comment by shysaur** [comment]
Fixed by 8a39bd8.
