### ISSUE TITLE
Bindings / KVO / KVC Discussion

### ISSUE THREAD

**Issue by balthisar** [shysaur/Fragaria#56]
@shysaur, I've been digging into a several possible solutions for observing one or more instances of Fragaria and tying it/them to the user defaults system. I've also learned a lot about the "magic" behind bindings in this journey. I would appreciate your feedback on direction (it has nothing to do with userDefaults at all, but bindings and KVO/KVC).

Summary:
- Direction (1): leave everything else alone and do all KVO/KVC externally. Easiest.
- Direction (2): make MGSFragaria bindings-compatible. Ugly, most difficult due to the many levels of responsible objects.
- Direction (3): Do KVO/KVC in MGSFragariaView and make _it_ bindings compatible. Irritating to do, but probably the most elegant from the user perspective.

Discussion:

Right now MGSFragaria and its properties are observable and settable via KVO/KVC, either via MGSFragaria directly or via its exposed components. From the scope of a new "MGSObserver" type of class, it's relatively trivial to observe the desired properties via KVO and set the desired properties via KVC.

Therefore direction (1) would be to handle all of this externally in this hypothetical optional class.

Currently MGSFragaria and its component classes inherit the default behavior for `bind:toObject:withKeyPath:options` from NSObject, which results in a one-way binding, i.e., MGSFragaria can observe an arbitrary model, but cannot provide updates to that model.

Obviously two-way binding is a nice feature to have (a "want"), but not a necessity to have (not a "need"). Additionally _adding_ it to the base Fragaria class would require (I think):
- adding the code to every top level component (the SMLTextView, etc.) so that they ALL implement the return binding.
- Or removing the dynamic properties and making every pertinent property part of base MGSFragaria again.

(Essentially the property setters have to all be able to check -[NSObject infoForBinding:] and update the model via KVC).

Therefore direction (2) would be to start re-implementing all of this so that MGSFragaria can be bindings compatible in both directions).

I rather abhor Direction (2) because it undoes a **lot** of leanness that you've introduced to MGSFragaria, but it _is_ a solution.

Direction (3) might be making MGSFragariaView fully bindings compatible. It can handle all of the manual KVO/KVC in Direction (1), and provide abstracted properties for everything relevant to MGSFragaria, without making MGSFragaria heavy again. 

I'd abandoned MGSFragariaView and there's a @todo suggesting no need to abstract MGSFragaria's properties, but if I do that then the class is only a minor convenience, especially after having removed embedInView:. If I add the properties back and make them bindings compatible, it suddenly becomes much more useful to other developers.

However the new hypothetical "MGSObserver" type of class would then only work with MGSFragariaView instead of MGSFragaria (which may be a good thing, as MGSFragaria still has the old defaults system to use).

I can make my proposed multiple-Fragaria-instances user defaults proposal work with any of the above. Any thoughts, or other ideas that I've not mentioned?

**Comment by shysaur** [comment]
Yeah, bindings are very convenient and I use them every time I can with Apple's views, but customizing them in any way always turns out difficult. 

Your 3rd option looks good to me. Don't overdo it though; even Cocoa's standard classes are binding-compatible for only few selected properties. Maybe you could implement in MGSFragariaView only those properties which are binding-compatible, leaving all other properties (which are to be accessed manually anyway) in MGSFragaria only, without duplicating them in MGSFragariaView (that would also get rid of the protocol you added in #57).

If we really want to remove one extra layer of indirection, we could easily kill MGSFragaria and keep MGSFragariaView only! MGSFragaria is basically an empty class, it just sets up its view hierarchy, and everything else it does is forwarded to somebody else. Also, this would solve the issue of having the framework's umbrella header coincide with MGSFragaria's header. This would also make the new Fragaria completely incompatible with the old one though... 

Obviously replacing MGSFragaria with MGSFragariaView is just an idea for the future; don't bother implementing it now.

**Comment by balthisar** [comment]
I'm considering making all of the properties bindable that are in the current nibs for the Preferences panels. This makes it simple to replace NSUserDefaultsController with any arbitrary controller and use the Preferences panels not just for preferences, but general view customization, too.

In current implementation when using the legacy defaults, as soon as a property is changed all instances of Fragaria take the same appearance. Making the current preferences panels more generic would allow them to work for single Fragaria instances in addition to user defaults, depending on what the controller is linked to.

Re: the protocol, I'm not stuck on having a protocol. It seemed less stupid than just copying and pasting MGSFragaria's header into another class. I would have adopted the protocol in MGSFragaria, too, and eliminate that code, but I didn't want to cause a WTF moment for you.

**Comment by shysaur** [comment]
Don't get me wrong, I don't think that having a protocol for the common API between MGSFragariaView and MGSFragaria is bad. For Fragaria's contributors, the protocol makes keeping MGSFragariaView and MGSFragaria in sync much easier, because Xcode should automatically flag what's missing in both classes for you. For Fragaria's users, it makes switching to MGSFragariaView from MGSFragaria a little easier (almost a drop-in replacement).

The real issue is that – from the framework users' perspective – MGSFragariaView and MGSFragaria do the same thing, and thus having both is redundant. Eventually, when the time comes to make MGSFragaria (class) rest in peace, MGSFragariaView will take its place, and then that protocol will not be needed anymore. But in the meantime having the protocol is a good thing, because it eases the transition.

Back to bindings. I'm sorry I forgot your reasons when writing that answer! Having a lot of bindings is OK for me, even if that means a lot of copy-pasted accessor overrides.

**Comment by balthisar** [comment]
> The real issue is that – from the framework users' perspective – MGSFragariaView and MGSFragaria do the same thing, and thus having both is redundant.

It's kind of funny how it evolved that way; I only added it in the first place so I could set the delegate in IB and avoid having to manually call embedInView. I think all of the changes you made to MGSFragaria to simplify it kind of made them merge into being nearly 100% redundant now. Of course MGSFragaria still have much of the legacy support, so it's good to keep around for the time being.
