### ISSUE TITLE
References frameworks are missing '@rpath/Fragaria.framework'

### ISSUE THREAD

**Issue by softmastx** [shysaur/Fragaria#96]
I have feed back from apple review 

> Your app references frameworks which are missing. This may lead to unexpected bugs or undefined behavior. The missing framework is '@rpath/Fragaria.framework'
> 
> We discovered one or more bugs in your app when reviewed on Mac running **macOS 10.12**

**It's work very well on OSX 10.11.**
I don't have macOS Seirra for testing!    I think the problem is on **new macOS** , anybody experienced this issue? 

Thanks

**Comment by shysaur** [comment]
This looks like a bug in your app's build settings rather than a bug in Fragaria. Please check that:
- you are copying `Fragaria.framework` inside your application bundle's `Frameworks` folder with an appropriate _Build Phase_
- in your app's _Build Settings_, the "Runpath Search Paths" option is set to `@executable_path/../Frameworks`

Then select Clean from the Product menu before building again.

Note that **even if your project's build settings are not correct, the app might run anyway when launched from Xcode**, because Xcode sets `@rpath` to the build products folder, and incidentally this is where Fragaria.framework is placed when it's built, alongside your app. This is probably why app review found a problem and you did not.

By moving the application bundle outside of the build products directory and launching it, you can easily verify if the framework was correctly copied and linked during the build. If it was not, the application will crash immediately, and in the crash log you'll be able see the same error that app review reported. (In the log it will appear as `Dyld Error Message:` `Library not loaded: @rpath/Fragaria.framework/Fragaria`)

The "We discovered one or more bugs in your app when reviewed on Mac running macOS 10.12" sentence is just a standard copy-pasta that does not imply in any way that the app was found to work in any other macOS version by app review.

I tested Fragaria on macOS Sierra as soon as it came out, and I could not find any compatibility issue. Sierra does not change the framework loading rules, and the working directory randomisation introduced in Sierra does not affect loading properly linked frameworks, so any problem related to linking will be easily reproducible on any other reasonably recent macOS version as well.

Feel free to reopen this bug if the steps I outlined above do not resolve your problem.
