### ISSUE TITLE
Autocomplete only when selecting a value from the suggestions list?

### ISSUE THREAD

**Issue by alexmocanu** [shysaur/Fragaria#98]
Is it possible to make the autocomplete functionality update the text in the editor only after I manually select a option from the suggestion list and press Enter? 

Currently, for example, in SQL mode when I start typing "sel" the "SELECT" keyword appears in the suggestions list, is automatically selected and the current word in the editor changes from "sel" to "SELECT". The only way to revert back to the original text is to press Escape to hide the suggestions list. 

What I need is the text to change only after I manually selected the desired option (SELECT in this case) and pressed Enter (or selected it with the mouse).

**Comment by shysaur** [comment]
Fragaria does not provide any setting to get the behaviour you want yet. At the moment I do not have the time to add it to Fragaria, but I think you can implement it yourself in the following way:
1. Make your own fork of Fragaria
2. In SMLTextView, override the [-insertCompletion:forPartialWordRange:movement:isFinal:](https://developer.apple.com/documentation/appkit/nstextview/1449448-insertcompletion?language=objc) method of NSTextView, so that it does not insert the completed word when isFinal is NO

**Comment by alexmocanu** [comment]
It works as suggested. Overriding that method did exactly what I needed.
Here is a pull request with this change, it might need some more refining since I don't know any Objective C (I only do Swift): #99

**Comment by shysaur** [comment]
Fixed by afc8da2.
